language: python

python:
  - "3.7"

cache: pip

install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
  - pip install -e .[ci]

script:
  - pytest --cov --cov-report term-missing:skip-covered

after_success:
  - coveralls
